### ISSUE TITLE
api怎么引用？

### ISSUE THREAD

**Issue by XinJiangQingMang** [Jesonhu/vuecli3-project-quick-start#2]

**Comment by Jesonhu** [comment]
@mcmf 

由于设置了 `Vue.prototype.$http = api`
组件里面 this.$http 就能使用 `api`

而且在 `mian.js` 也引入了 api
[源码地址](https://github.com/Jesonhu/vuecli3-project-quick-start/blob/master/src/api/index.js)

**Comment by XinJiangQingMang** [comment]
然后像getBanner  怎么用呢  

import { getBanner   } from '@/api

...


getBanner().then(res => {
})


这样好像不对呢

**Comment by Jesonhu** [comment]
这样使用 
> import Api from '@/api';

**Comment by XinJiangQingMang** [comment]
@Jesonhu 谢谢！

**Comment by Jesonhu** [comment]
组件里面 `this.$http` 应该也能用，不用每次都要引入
